services:
  mongo:
    image: mongo:6
    container_name: yelp-mongo
    command: [ "mongod", "--logpath", "/dev/null" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: yelp-app
    depends_on:
      - mongo
    volumes:
      - .:/app
      - ./data/raw:/data/raw:ro
    ports:
      - "8501:8501"
    entrypoint: ["/bin/bash", "scripts/entrypoint.sh"]

volumes:
  mongo_data:
